language: php
sudo: false

git:
  depth: 2

matrix:
  include:
    - php: 7.0
      env:
        - LINT=true COVERAGE=true
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge

  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm-3.9

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - source .travis/xdebug.sh
  - xdebug-disable

before_script:
  - travis_retry composer update --no-interaction --prefer-source --prefer-stable

script:
  - if [[ "$LINT" == "true" ]]; then
      composer cs-lint;
      composer sa;
    fi
  - if [[ "$COVERAGE" == "true" ]]; then
      xdebug-enable;
      vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover;
      xdebug-disable;
    else
      vendor/bin/phpunit;
    fi

after_script:
  - if [[ "$COVERAGE" == "true" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar;
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
